---
# ASSUMPTION: any necessary boostrapping has already been done.
- name: install pbench.repo
  hosts: servers
  remote_user: root
  become: yes
  become_user: root

  roles:
    - pbench-repo-install
    - { role: rhel8-cert-install, when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8' }
